package:
  name: pythreejs
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}

source:
  path: ../

requirements:
  build:
    - python

  run:
    - python
    - jupyter

test:
  # Python imports
  imports:
    - pythreejs

about:
  home: https://github.com/jovyan/pythreejs
  license: BSD
  summary: 'Interactive 3d graphics for the Jupyter notebook, using Three.js from IPython widgets.'
